name: Pantheon Build
on:
  push:
    branches:
      - main

jobs:
  github_deploy_to_dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pantheon Deploy
      uses: pantheoncarl/code-deploy-wp@main
      id: cache-vendor
      env:
        CARKONEMAIL: ${{ secrets.PANTHEONEMAIL }}
        PANTHEONSITEUUID: 4a2be46c-9101-45d4-b51b-cd342c7b3d7f
        PANTHEONEMAIL: carl.alberto@pantheon.io
        MACHINETOKEN: ${{ secrets.MACHINETOKEN }}
        PANTHEON_PRIVATE_KEY: ${{ secrets.PANTHEON_PRIVATE_KEY }}
        PROJECT_ROOT: $(pwd)
        GH_REF2: ${{ github.ref }}
        PANTHEONENV: dev
    - name: Composer build and deploy
      id: cache-composer
      run: |
        echo $CARKONEMAIL
        echo "$CARKONEMAIL"
        echo CARKONEMAIL
        ls
        pwd
        cd /
        ls
        terminus
        cd /home/runner/work


      # sh $PROJECT_ROOT/scripts/github/build-wp-composer-partial
      # run: |

      #   pwd
      #   ls
      #   #terminus info
      #   cd /home
      #   pwd
      #   ls
      #   cd ~
      #   ls
      #   echo 'homeeeeeee'
      #   cd /home/runner/work
      #   ls
      #   composer
        
        # export PROJECT_ROOT="$(pwd)"
        # . $PROJECT_ROOT/config  

        # sh $PROJECT_ROOT/scripts/github/load-variables

        # sh $PROJECT_ROOT/scripts/github/setup-terminus

        # printf "[\e[0;34mNOTICE\e[0m] Terminus Setup COMPLETE!!!.\n"
        # ls

    # - name: Composer build and deploy
    #   id: cache-composer
    #   run: |
    #     export PROJECT_ROOT="$(pwd)"
    #     . $PROJECT_ROOT/config  

    #     # sh $PROJECT_ROOT/scripts/github/setup-terminus

        
    #     sh $PROJECT_ROOT/scripts/github/build-wp-composer
    #     ls





    # - name: Save Vender folder
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: vendor-data
    #     path: vendor

    # - name: Save WP compiled
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: wp-compiled
    #     path: web
    
    # - name: Save WP custom
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: wp-compiled
    #     path: web/wp-content/themes


