name: My Action

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Pull Docker Image
        run: docker pull quay.io/pantheon-public/build-tools-ci:8.x-php7.4

      - name: Run Docker Container
        run: |
          docker run -it \
            -v $(pwd):/app \
            -w /app \
            quay.io/pantheon-public/build-tools-ci:8.x-php7.4 \
            bash -c "echo 'Hello, world!'; ls"
