name: Pantheon Build
on:
  push:
    branches:
      - main

jobs:
  github_deploy_to_dev:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pantheon Deploy
      uses: pantheoncarl/code-deploy-wp@main
      id: cache-vendor
      env:
        CARKONEMAIL: ${{ secrets.PANTHEONEMAIL }}
        PANTHEONSITEUUID: 4a2be46c-9101-45d4-b51b-cd342c7b3d7f
        PANTHEONEMAIL: carl.alberto@getpantheon.com
        PANTHEON_TERMINUS_MACHINE_TOKEN: ${{ secrets.PANTHEON_TERMINUS_MACHINE_TOKEN }}
        PANTHEON_PRIVATE_KEY: ${{ secrets.PANTHEON_PRIVATE_KEY }}
        PROJECT_ROOT: $(pwd)
        GH_REF2: ${{ github.ref }}
        PANTHEONENV: dev
    - name: Composer build and deploy
      id: cache-composer
      run: |
        echo $CARKONEMAIL
        ls
        export SITENAME="$(terminus site:info  --format list --field name -- $PANTHEONSITEUUID)"
        echo $SITENAME
        echo $PANTHEONSITEUUID
        terminus rsync . $SITENAME.dev:code
        pwd
        cd /
        ls
        terminus whoami
        eval `ssh-agent -s`


